### ISSUE TITLE
Bytecode __pycache__ directory included 

### ISSUE THREAD

**Issue by jrbourbeau** [mattmeehan/catdog#1]
Just a friendly heads up, it looks like a bytecode `__pycache__` directory is included in the `catdog` package. You may consider adding some of the contents from the [GitHub Python .gitignore file](https://github.com/github/gitignore/blob/master/Python.gitignore) to the `.gitignore` file for this repo.

**Comment by mattmeehan** [comment]
Ah, thanks for catching that! I added the .gitignore _after_ I had already commited the that. Fixed!
